# Generated by Django 2.1.2 on 2018-10-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('actualNickName', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=9999)),
            ],
        ),
    ]
