# Generated by Django 2.1.2 on 2018-11-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('msgId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg2db.Msg')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openId', models.CharField(max_length=200)),
                ('actualNickName', models.CharField(max_length=200)),
                ('telNum', models.CharField(max_length=200)),
                ('joinTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msg2db.User'),
        ),
    ]
