# Generated by Django 2.1.2 on 2018-11-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0002_auto_20181107_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='msgId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msg', to='msg2db.Msg'),
        ),
        migrations.AlterField(
            model_name='note',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to='msg2db.User'),
        ),
    ]
