# Generated by Django 2.1.2 on 2018-11-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0003_auto_20181107_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telNum',
        ),
        migrations.AddField(
            model_name='user',
            name='cellPhoneNumber',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='chineseName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='employmentNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='msg',
            name='actualNickName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='msg',
            name='nickName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='msg',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='actualNickName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='openId',
            field=models.CharField(max_length=100),
        ),
    ]
