# Generated by Django 2.1.2 on 2018-11-09 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0005_auto_20181108_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='openId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='openid', to='msg2db.User'),
        ),
    ]
