# Generated by Django 2.1.2 on 2018-11-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0006_note_openid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='openId',
        ),
    ]
