# Generated by Django 2.1.2 on 2018-11-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0008_remove_user_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='addOnMsg',
        ),
    ]
