# Generated by Django 2.1.2 on 2018-11-09 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0009_remove_user_addonmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='msgId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msg_id', to='msg2db.Msg'),
        ),
        migrations.AlterField(
            model_name='note',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to='msg2db.User'),
        ),
    ]
