# Generated by Django 2.1.2 on 2018-11-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0010_auto_20181109_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='userID',
            new_name='userId',
        ),
    ]
