# Generated by Django 2.1.2 on 2018-11-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg2db', '0011_auto_20181109_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('msgId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msg_id_in_comment', to='msg2db.Msg')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id_in_comment', to='msg2db.User')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgUrl', models.CharField(max_length=500)),
                ('addTime', models.DateTimeField(auto_now_add=True)),
                ('msgId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='msg_id_in_image', to='msg2db.Msg')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id_in_image', to='msg2db.User')),
            ],
        ),
    ]
